# Normally this file would be .gitignore and secrets
# For the sake of this exercise, I assume it is fine to store it plaintext here

auth:
  tokens:
   - Wu9Mae7U
   - ohwe9Sec

ratelimit:
  private_token:
    limit: 200
    period: 3600
  public_ip:
    limit: 100
    period: 3600
